class Benefit

  @@benefits = [
      'my data is not lost',
      'I can help others out',
      'I can share my opinions with friends',
      'the quality of the result is ensured',
      'it is convenient for me for the time being',
      'I can test the product before I actually buy it',
      'I know which features are the most welcome',
      'I can send it to someone else',
      'I know when to call my support team',
      'I can track the status of the job',
      'I can hand it over to other people',
      'everybody knows what the status is',
      'I know what they are doing',
      'I can get back to it later',
      'valuable elements can be easily found',
      'I know what they are up to',
      'it\'s convenient for me to use the application',
      'they can handle it or decide what to do with it',
      'everybody knows that I\'m the best',
      'I can sleep well tonight',
      'I keep track of my money',
      'I take control over the world',
      'the connection pool is never too small',
      'I won\'t forget about it',
      'they know what to do with it',
      'I can quickly find the data that I need',
      'the implementation can be changed',
      'I can embed those on my website',
      'the system is stable under any circumstances',
      'I have all my files sound and safe',
      'I can return the item if I don\'t like it',
      'my boss is happy',
      'it is easy to maintain it',
      'we can measure the impact over time',
      'someone can take the task over',
      'it never happens again',
      'my ego is satisfied',
      'the output is human-readable',
      'the system is environment-friendly',
      'the message can be understood by chimps',
      'other people want to buy it too',
      'the competition is jealous',
      'events are propagated to other actors',
      'with no worries I can come back to it later',
      'I can put emphasis on certain aspects',
      'the system is PCI-compliant',
      'I understand what is going to happen',
      'I sell more',
      'other people can benefit from it',
      'the site is looks more attractive for the teenagers',
      'I don\'t have to remember all of that',
      'my actions are transparent to others',
      'there is single official version of the document',
      'I see right away what the costs are',
      'the customers don\'t feel confused',
      'others can motivate me to get things done',
      'all available options are one click away',
      'my highlighted items are displayed here and there',
      'can try things out without any worries',
      'Facebook users can actually use the product',
      'I get faster feedback from the people',
      'I can impress that girl over there',
      'settle on a decent deal',
      'I can roll out the changes in no time',
      'I get to the important part quickly',
      'I can proceed seamlessly',
      'I can adjust the behavior for the needs of my domain',
      'I avoid vendor locking',
      'I can react on time',
      'I don\' have to deal with it myself',
      'I cut the costs down after all',
      'I get the most discounts and benefits',
      'I can gain respect in the community',
      'they can interact with each other',
      'the process is optimized and efficient',
      'I\'m not the one who takes the responsibility',
      'the content is well-organized',
      'I won\'t do it ever again',
      'they get an impression of self-development',
      'I don\'t waste so much time on it',
      'I prevent random errors',
      'I don\'t run out of resources',
  ]

  def self.get
    @@benefits.sample
  end
end