class Goal

  @@goals = [
      'log into the main dashboard',
      'enroll on the selected course',
      'put my comments',
      'generate invoices for completed transactions',
      'install third-party plugins',
      'customize the layout for my needs',
      'log in with Facebook',
      'translate the documents into other languages',
      'withdraw money from my account',
      'trace the activity of my friends',
      'share my achievements with others',
      'win badges for certain achievements',
      'create bookmarks',
      'monitor the data throughput',
      'provision the virtual machine',
      'label my files with arbitrary tags',
      'export the page to PDF',
      'adjust the image parameters',
      'read the messages of other users',
      'mark the content as private',
      'sign the documents',
      'move on to the next task',
      'put the advertisements on selected websites',
      'perform batch operations on the items',
      'change my privacy settings',
      'easily share the URLs across the web',
      'collaborate on the spreadsheets with other members',
      'vote for correct answers',
      'assign notes for every result',
      'use keyboard shortcuts to navigate through the app',
      'use gestures to operate the system',
      'subscribe for future updates',
      'answer to existing questions',
      'pass my ownership to someone else',
      'use markup language in my posts',
      'put items to the basket',
      'rate and write opinions on items',
      'attach arbitrary data',
      'submit my solution for the problem',
      'trigger processing with an API call',
      'deploy the whole system with one click',
      'perform A/B tests on the beta features',
      'check out previous revisions',
      'call the whole thing off at any moment',
      'sign up with my email',
      'send SOS signals if something goes wrong',
      'change the setting of any account',
      'find any item using a search form',
      'perform a general health-check',
      'import my setting from an external source',
      'detect duplicate or misspelled names',
      'handle 1k transactions per second',
      'synchronize the data with other devices',
      'use a stylus to point and click',
      'signal warnings to the administrators',
      'make payments using the default bank account',
      'send event reminders compatible with Google Calendar',
      'approve the content for further processing',
      'adjust the processing flow',
      'fine-tune the business rules',
      'pay with bitcoins',
      'send paper invitations to the premium partners',
      'see the monthly report',
      'share my screen over the internet',
      'save the progress at any time',
      'call the support operator',
      'watch the stars',
      'shutdown safely and gracefully',
      'make new connections',
      'collect binary data',
      'download the assets for free',
      'star items that I find interesting',
      'subscribe to a channel',
      'tweet about the event',
      'always go back in my browsing history',
      'filter the table by tags',
      'undo my actions',
      'return to the home screen',
      'delete my account',
      'scale out to 100s of instances',
      'migrate the whole environment to a newer version',
      'follow other users',
      'mention other handles',
      'send direct messages to my peers',
      'upload photos of choice',
      'live stream the camera image over the net',
      'update my personal information',
      'change my avatar via Gravatar',
      'choose what to print and in what quantities',
      'prevent entry duplicates in batches',
      'prevent chaos',
      'watch my stocks go up',
      'compete with my peers',
      'boast off with my results on other websites',
      'make a list of queued songs',
      'skip the most complicated parts of the course',
      'respond with a redirect',
      'offer a discount based on my privileges',
      'introduce my custom rules for handling error situations',
      'let my keyboard cat play around',
      'accept invitations from people I know',
      'play offline',
      'rebalance all the existing nodes',
      'get a free trial with a sample showcase',
      'haz cheezburger',
      'optimize my phone bills',
      'choose a silver plan',
      'lease processing power and resources',
      'rent flats to trusted clients',
      'locate other devices',
      'charge additional fees for extra services',
      'detach the add-on at any time',
      'blame the developers for every bug',
  ]

  def self.get
    @@goals.sample
  end
end