class Goal

  @@goals = [
      'log into the easter egg dashboard',
      'see purchased items in augmented reality',
      'customize this sad-looking table layout',
      'trace (and mock at) the activity of my enemies',
      'win badges for certain achievements',
      'create non-deterministic bookmarks',
      'export the articles to PDFs and proper PHDs',
      'mark the content as PEGI-18 / probably illegal / illegal for sure',
      'sign the documents with a stacktrace',
      'perform batch operations on my groceries',
      'change my NSA settings in a Facebook-ish way',
      'easily share shortened, yet memorable URLs across the web',
      'assign funny cat pics for every ticket',
      'subscribe only for the good news',
      'pass my ownership over to someone else and therefore avoid mockery and condemnation',
      'inject executable javascript snippets in my posts',
      'toss items to the basket and watch them collide',
      'rate and comment with meme images',
      'kill the gray zone servers with an emergency button',
      'call the whole thing off at any moment',
      'sign up with my fingerprint or whatever-print',
      'beep SOS signals just to get more attention',
      'let Hubot perform an overall system health-check for me',
      'import my colour-schema from Eclipse',
      'handle 1k transactions per second (TBD: "handle")',
      'synchronize the acquired intelligence with other spy devices',
      'use a stylus to command and conquer',
      'signal experimental warnings to the cabin crew',
      'use Maven or Rake tasks to dig for bitcoins',
      'send BBQ reminders compatible with Google, BB10 and sender\'s company culture',
      'fine-tune the business rules to fit the needs of my superiors',
      'pay the electricity bills with Story Points',
      'send paper invitations to the premium partners and recycled-paper invitations to the regular ones',
      'share my screen, mouse and keyboard over the internet',
      'call me maybe',
      'request a random gif of the wow shibe doge',
      'undo the undone',
      'delete my account',
      'scale out to 100s of instances',
      'stalk other users',
      'live stream the phone cam over the net',
      'prevent entry duplicates at the main entrance gate',
      'compete with other companies\' employees',
      'boast off with my badges on other websites',
      'offer a discount based on my mood and possibly also my privileges',
      'let my keyboard cat play around',
      'accept challenge invitations from people I compete with',
      'haz cheezburger',
      'optimize my adult-site bills',
      'geo-locate other devices that are nearby',
  ]

  def self.get
    @@goals.sample
  end
end