class Role

  @@roles = [
      'User',
      'Member',
      'Product Owner',
      'Administrator',
      'Client Application',
      'Caller',
      'Callee',
      'Referrer',
      'Referee',
      'Web Crawler',
      'Customer',
      'Maintainer',
      'Stakeholder',
      'System',
      'Placeholder',
      'Web Browser',
      'Container',
      'Plugin',
      'Host Application',
      'Peer',
      'Server',
      'Handler',
      'Participant',
      'Collaborator',
      'Third Party',
      'External Source',
      'Operation Target',
      'Controller',
      'Visitor',
      'Subscriber',
      'Transmitter',
      'Receiver',
      'Contributor',
      'Voter',
      'Owner',
      'Author',
      'Partner',
      'Follower',
      'Publisher',
      'Producer',
      'Consumer',
      'Student',
      'Passenger',
      'Manager',
      'Designer',
      'Developer',
      'Parent',
      'Driver',
      'Passenger',
      'Adviser',
      'Staff Member',
      'Employee',
      'Employer',
      'Teacher',
      'Consultant',
      'Salesperson',
      'Writer',
      'Representative',
      'Musician',
      'Photographer',
      'Community Member',
      'Institution',
      'Organization',
      'Company',
      'Group Leader',
      'Person',
      'Vendor',
      'Recipient',
      'Instance',
      'Cluster Node',
      'WebService',
      'Platform',
  ]

  def self.get
    @@roles.sample
  end
end