class Role

  @@roles = [
      'User',
      'Member',
      'Product Owner',
      'Administrator',
      'Client Application',
      'Passenger',
      'Customer',
      'Bookkeeper',
      'Accountant',
      'Manager',
      'Designer',
      'Developer',
      'Parent',
      'Driver',
      'Pharmacist',
      'Web Crawler',
      'Architect',
      'Engineer',
      'Lawyer',
      'Nurse',
      'Scientist',
      'Surgeon',
      'Teacher',
      'Actor',
      'Economist',
      'Consultant',
      'Construction Worker',
      'Salesperson',
      'Stakeholder',
      'System',
      'Writer',
      'Driver',
      'Representative',
      'Placeholder',
      'Web Browser',
      'Container',
      'Librarian',
      'Plugin',
      'Host Application',
      'Peer',
      'Referee',
      'Adviser',
      'Server',
      'Handle',
      'Participant',
      'Collaborator',
      'Songwriter',
      'Musician',
      'Third Party',
      'External Source',
      'Operation Target',
      'Controller',
      'Visitor',
      'Subscriber',
      'Voter',
      'Judge',
      'Owner',
      'Author',
      'Photographer',
      'Bartender',
      'Community'
  ]

  def self.get
    @@roles.sample
  end
end